apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: molecule-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: molecule-service
          servicePort: 80
