apiVersion: v1
kind: Secret
metadata:
  name: boomi-secret
type: Opaque
stringData:
  account: {{ .Values.secrets.account }}
  {{ if eq "token" .Values.auth.type }}
  token: {{ .Values.secrets.token }}
  {{ else }}
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
  {{ end }}
