apiVersion: v1
kind: Secret
metadata:
  name: boomi-secret
type: Opaque
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
  account: {{ .Values.secrets.account }}
