apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
