---
auth:
  type: password

secrets:
  account: testaccount
  username: testuser
  password: testpassword
  token: testtoken

volume:
  path: /boomifileshare
  server: 10.0.0.8

storage:
  reservedIpRange: 10.0.0.8/29
  network: default
