{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nfs-client-provisioner.name" . }}
    chart: {{ template "nfs-client-provisioner.chart" . }}
    heritage: {{ template "nfs-client-provisioner.chart" . }}
    release: {{ template "nfs-client-provisioner.chart" . }}
  name: {{ template "nfs-client-provisioner.serviceAccountName" . }}
{{- end -}}
