imports:
- path: ../boomi_molecule_existing_vpc.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule_existing_vpc.jinja
  properties:
    zone: us-central1-a
    gkeClusterNetwork: default
    gkeClusterPrivateSubnetwork: default
    gkeClusterPublicSubnetwork: default
    secretEmailID: boomiUserEmailID
    secretPassword: boomiPassword
    secretAccountID: boomiAccountID

