imports:
- path: ../boomi_molecule.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule.jinja
  properties:
    zone: us-central1-a
    boomiUserEmailID: boomiUserEmailID
    boomiPassword: boomiPassword
    boomiAccountID: boomiAccountID
    subnetCidrOne: 192.168.0.0/21
    subnetCidrTwo: 192.168.8.0/21
