imports:
- path: ../boomi_molecule_existing_vpc.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule_existing_vpc.jinja
  properties:
    zone: us-central1-a
    network: sravopen-vpc-dev
    vmSubnetwork: sravopen-private-0-dev
    gkeSubetwork: sravopen-private-1-dev
    boomiUserEmailID: boomiUserEmailID
    boomiPassword: boomiPassword
    boomiAccountID: boomiAccountID
