imports:
- path: ../boomi_molecule_existing_vpc.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule_existing_vpc.jinja
  properties:
    zone: us-central1-a
    network: default
    vmSubnetwork: default
    gkeSubetwork: default
    boomiUserEmailID: boomiUserEmailID
    boomiPassword: boomiPassword
    boomiAccountID: boomiAccountID

