imports:
- path: ../boomi_molecule.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule.jinja
  properties:
    zone: us-central1-a
    secretEmailID: boomiUserEmailID
    secretPassword: boomiPassword
    secretAccountID: boomiAccountID
